stages:
- build
- test
- deploy

coverage:
  stage: test
  image: golang:1.16
  tags:
  - docker
  script:
  - go mod download
  - go test $(go list ./... | grep -v /vendor/) -v -coverprofile .testCoverage.txt

.go-cache:
  variables:
    GOPATH: $CI_PROJECT_DIR/.go
  before_script:
    - mkdir -p .go
  cache:
    paths:
      - .go/pkg/mod


test:golangci-lint:
  stage: test
  image: golangci/golangci-lint:v1.41.1
  allow_failure: true
  extends: .go-cache
  script:
    - go version
    - go mod download
    - make lint

sast:
  stage: test
include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/License-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
